version: "3.3" 
services:
  mongo:
    build: ./Dockerfiles/Mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      app:
        ipv4_address: 11.0.0.6

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      app:
        ipv4_address: 11.0.0.15

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
      - "9092:9092"
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: 11.0.0.4
      KAFKA_CREATE_TOPICS: "flight_delay_classification_request:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      app:
        ipv4_address: 11.0.0.4

  web:
    container_name: flask-python
    build: ./Dockerfiles/Flask
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/app/
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/kafka:/kafka
    networks:
      app:
        ipv4_address: 11.0.0.3

  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      spark:
        ipv4_address: 10.0.0.2

  spark-worker-1:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
      - model
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      spark:
        ipv4_address: 10.0.0.3

  model:
    build: ./Dockerfiles/SparkScala
    depends_on:
      - spark-master
    networks:
      spark:
        ipv4_address: 10.0.0.4
      app:
        ipv4_address: 11.0.0.2

networks:
  spark:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16 
  app:
    driver: bridge
    ipam:
      config:
        - subnet: 11.0.0.0/16
       
    
      
      

